CREATE DATABASE iot;
CREATE USER 'iot'@'%' IDENTIFIED BY 'iot-pass';
GRANT ALL PRIVILEGES ON nome_do_banco.* TO 'iot'@'localhost';
FLUSH PRIVILEGES;
USE iot;
CREATE TABLE sensor (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- Usar PRIMARY KEY com AUTO_INCREMENT
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Usar CURRENT_TIMESTAMP para a data e hora
    value JSON NOT NULL
);
