CREATE DATABASE iot;
USE iot;
CREATE TABLE sensor (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- Usar PRIMARY KEY com AUTO_INCREMENT
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Usar CURRENT_TIMESTAMP para a data e hora
    value JSON NOT NULL
);
